### ISSUE TITLE
question about NaN

### ISSUE THREAD

**Issue by massemanet** [deadtrickster/prometheus.erl#36]
noticed this output from the system info collector. Shouldn't the value be NaN in this case?

```
# TYPE erlang_vm_logical_processors_available gauge
# HELP erlang_vm_logical_processors_available The detected number of logical processors available to the Erlang runtime system
erlang_vm_logical_processors_available unknown

```

**Comment by deadtrickster** [comment]
Good spot! I didn't pay enough attention to return values and thought it's always either number or undefined.

**Comment by deadtrickster** [comment]
should be fixed in version-3 branch. Can't test though, I always got numbers

**Comment by massemanet** [comment]
I'm running on Darwin...

Suggestion; 
change prometheus_text_format:emit_series to print "NaN" when called with a non-number;
```
emit_series(Fd, Name, Labels, Value) when is_number(Value) ->
   ...; %number
emit_series(Fd, Name, Labels, _) ->
   ...  % not number
```

**Comment by deadtrickster** [comment]
Yea, I'm on linux. 

Thank you for the suggestion, however I don't think this is right thing to do, because we also have protobuf format which actually drives models representation. And it understands numbers or `undefined`, nan and infinities (e.g. https://github.com/deadtrickster/prometheus.erl/blob/master/include/prometheus_model.hrl#L30). For +Inf I'm using terms ordering hack, -Inf and NaN, I'm not sure these can be produced by Erlang right now. So only `undefined` left. Probably could be replaced by `'NaN`' in the future, hard to say now, it's very handy as NaN because it's the default for many getters. 

Have you tried the fix? Does it work for you?

**Comment by massemanet** [comment]
I'll try your fix later today.

looking at prometheus_model:e_msg_Counter it seems it handles numbers, 'infinity', '-infinity' and 'nan' as expected, 'undefined' some other way(?), and crashes otherwise. crashing seems a bit brutal; do you handle that some other place?

**Comment by deadtrickster** [comment]
Prometheus_model actually generated from https://github.com/prometheus/client_model/blob/master/metrics.proto by gpb. Counter value is declared like this: ` optional double value = 1;` so `infinity`, `-infinity` and `nan` emulates missing floating point constants and `undefined` because value is optional. Prometheus docs states it's not a good idea to have metrics that can suddenly disappear and I still do not have use case for this. And as I observed stdlib and other OTP apps usually follow undefined-as-no-value convention, so I'm using undefined as NaN.

**Comment by massemanet** [comment]
I think using undefined to mean NaN is great. Problem is what should happen if one by mistake sets a value to some other random atom. If I understand it correctly, the text format will just print that atom, while the protobuf format will crash.

**Comment by massemanet** [comment]
running from version-3 HEAD I got this;

erlang_vm_logical_processors_available NaN

yay, closing.
