### ISSUE TITLE
Exometer integration?

### ISSUE THREAD

**Issue by hwinkel** [deadtrickster/prometheus.erl#50]
We are using exometer for metric collection of our projects. Is there a way to export exometer based metrics to prometheus. as we want to move toward prometheus based monitoring.

**Comment by deadtrickster** [comment]
Two options:
- move to prometheus.erl. Shouldn't be difficult really. Counters, Gauges, Histograms, Summaries are all common concepts. And thanks to Prometheus query language, there is no need to implement statistical stuff in prometheus.erl so it might be faster. Labels are awesome of course;
- write [prometheus collector](https://github.com/deadtrickster/prometheus.erl/blob/master/src/prometheus_collector.erl) (e.g.  [VM statistics collector](https://github.com/deadtrickster/prometheus.erl/blob/master/src/collectors/vm/prometheus_vm_statistics_collector.erl)). This collectot will transform existing exometer metrics to prometheus data model. Could be hard to utilize labels here and/or properly convert metrics (esp. complex, like histogram).

Personally, I'd move to prometheus.erl since it's simpler and of course more idiomatic. Thanks to Query Language no need to worry about statistics and data manipulation.

**Comment by hwinkel** [comment]
I'm still wondering a bit, is the query already against the  prometheus client endpoint or later in the prometheus server?

**Comment by deadtrickster** [comment]
Client endpoint just renders 'raw' values, like per-bucket counters. This later can be queried using PromQL against a Prometheus server.

**Comment by hwinkel** [comment]
@deadtrickster thats was my impression as well. Thanks
